name: Checkout
on: [push]

jobs:
    checkout-and-display-files:
        runs-on: ubuntu-latest
        steps:
            - name: List file before
              run: ls -a
            - name: Checkout
              run: |
                git init
                git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
                git fetch origin
                git checkout main
            - name: List file after
              run: ls -a